version = 1

exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**"
]

test_patterns = [
  "tests/**",
  "**/*.spec.*",
  "**/*.test.*"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

# Optional, if available on your plan:
[[analyzers]]
name = "security"
enabled = true
