name: PHPCS

on:
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpcs.xml.dist'
      - '.github/workflows/phpcs.yml'

permissions:
  contents: read

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=phpcs.xml.dist --report=checkstyle > phpcs-report.xml

      - name: Annotate PHPCS results
        uses: jwgmeligmeyling/checkstyle-github-action@a12be500c097a5cedab881d4785ef9b4a4d3ee6a
        with:
          path: phpcs-report.xml
