name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '37 7 * * *'

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci-report-only
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.162.0-nonroot@sha256:c9205060e5cefc26fe140f8d5ee477295c6d0724f9d15931a0a70f8272157064
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6
        with:
          persist-credentials: false

      - name: Run Semgrep in report-only mode
        run: semgrep ci || true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
